### ISSUE TITLE
App Frontends MVP

### ISSUE THREAD

**Issue by karimsa** [robinplatform/robin#12]
* [x] Get app pages to render in robin
* [x] Bundle app pages correctly for frontend (verify that ALL modules are resolved relative to the app and not robin core)
* [x] If bundling fails, render error correctly
* [x] If app crashes, render error correctly (with react-error-boundary)
* [ ] Communicate route changes correctly between robin and app page

**Comment by A1Liu** [comment]
Error boundary is almost done
Error checking all sorts of fucked
Route changes aren't done, neither are e.g. title changes

**Comment by A1Liu** [comment]
Error boundary basic version is done
Implemented 404 error page

**Comment by A1Liu** [comment]
I think this is done enough to be an MVP
